/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BetDwarkaRouteImport } from './routes/bet-dwarka'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as DharamshalaBookingRouteImport } from './routes/dharamshala-booking'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HotelBookingRouteImport } from './routes/hotel-booking'
import { Route as NageshwarTempleRouteImport } from './routes/nageshwar-temple'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SightseeingRouteImport } from './routes/sightseeing'
import { Route as TaxiServiceRouteImport } from './routes/taxi-service'
import { Route as TempleDarshanRouteImport } from './routes/temple-darshan'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TourPackagesIndexRouteImport } from './routes/tour-packages.index'
import { Route as TourPackagesDwarka1DayRouteImport } from './routes/tour-packages.dwarka-1-day'
import { Route as TourPackagesDwarka2DaysRouteImport } from './routes/tour-packages.dwarka-2-days'
import { Route as TourPackagesDwarkaGujaratRouteImport } from './routes/tour-packages.dwarka-gujarat'
import { Route as TourPackagesDwarkaSomnathRouteImport } from './routes/tour-packages.dwarka-somnath'
import { Route as TravelGuideIndexRouteImport } from './routes/travel-guide.index'
import { Route as TravelGuideBestTimeToVisitRouteImport } from './routes/travel-guide.best-time-to-visit'
import { Route as TravelGuideDwarkaItineraryRouteImport } from './routes/travel-guide.dwarka-itinerary'
import { Route as TravelGuideDwarkaLocalTransportRouteImport } from './routes/travel-guide.dwarka-local-transport'
import { Route as TravelGuideDwarkaToSomnathRouteImport } from './routes/travel-guide.dwarka-to-somnath'
import { Route as TravelGuideHowToReachDwarkaRouteImport } from './routes/travel-guide.how-to-reach-dwarka'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BetDwarkaRoute = BetDwarkaRouteImport.update({
  id: '/bet-dwarka',
  path: '/bet-dwarka',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const DharamshalaBookingRoute = DharamshalaBookingRouteImport.update({
  id: '/dharamshala-booking',
  path: '/dharamshala-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelBookingRoute = HotelBookingRouteImport.update({
  id: '/hotel-booking',
  path: '/hotel-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const NageshwarTempleRoute = NageshwarTempleRouteImport.update({
  id: '/nageshwar-temple',
  path: '/nageshwar-temple',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SightseeingRoute = SightseeingRouteImport.update({
  id: '/sightseeing',
  path: '/sightseeing',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiServiceRoute = TaxiServiceRouteImport.update({
  id: '/taxi-service',
  path: '/taxi-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TempleDarshanRoute = TempleDarshanRouteImport.update({
  id: '/temple-darshan',
  path: '/temple-darshan',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesIndexRoute = TourPackagesIndexRouteImport.update({
  id: '/tour-packages/',
  path: '/tour-packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesDwarka1DayRoute = TourPackagesDwarka1DayRouteImport.update({
  id: '/tour-packages/dwarka-1-day',
  path: '/tour-packages/dwarka-1-day',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesDwarka2DaysRoute = TourPackagesDwarka2DaysRouteImport.update({
  id: '/tour-packages/dwarka-2-days',
  path: '/tour-packages/dwarka-2-days',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesDwarkaGujaratRoute =
  TourPackagesDwarkaGujaratRouteImport.update({
    id: '/tour-packages/dwarka-gujarat',
    path: '/tour-packages/dwarka-gujarat',
    getParentRoute: () => rootRouteImport,
  } as any)
const TourPackagesDwarkaSomnathRoute =
  TourPackagesDwarkaSomnathRouteImport.update({
    id: '/tour-packages/dwarka-somnath',
    path: '/tour-packages/dwarka-somnath',
    getParentRoute: () => rootRouteImport,
  } as any)
const TravelGuideIndexRoute = TravelGuideIndexRouteImport.update({
  id: '/travel-guide/',
  path: '/travel-guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelGuideBestTimeToVisitRoute =
  TravelGuideBestTimeToVisitRouteImport.update({
    id: '/travel-guide/best-time-to-visit',
    path: '/travel-guide/best-time-to-visit',
    getParentRoute: () => rootRouteImport,
  } as any)
const TravelGuideDwarkaItineraryRoute =
  TravelGuideDwarkaItineraryRouteImport.update({
    id: '/travel-guide/dwarka-itinerary',
    path: '/travel-guide/dwarka-itinerary',
    getParentRoute: () => rootRouteImport,
  } as any)
const TravelGuideDwarkaLocalTransportRoute =
  TravelGuideDwarkaLocalTransportRouteImport.update({
    id: '/travel-guide/dwarka-local-transport',
    path: '/travel-guide/dwarka-local-transport',
    getParentRoute: () => rootRouteImport,
  } as any)
const TravelGuideDwarkaToSomnathRoute =
  TravelGuideDwarkaToSomnathRouteImport.update({
    id: '/travel-guide/dwarka-to-somnath',
    path: '/travel-guide/dwarka-to-somnath',
    getParentRoute: () => rootRouteImport,
  } as any)
const TravelGuideHowToReachDwarkaRoute =
  TravelGuideHowToReachDwarkaRouteImport.update({
    id: '/travel-guide/how-to-reach-dwarka',
    path: '/travel-guide/how-to-reach-dwarka',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/bet-dwarka': typeof BetDwarkaRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact-us': typeof ContactUsRoute
  '/dharamshala-booking': typeof DharamshalaBookingRoute
  '/faq': typeof FaqRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/nageshwar-temple': typeof NageshwarTempleRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sightseeing': typeof SightseeingRoute
  '/taxi-service': typeof TaxiServiceRoute
  '/temple-darshan': typeof TempleDarshanRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tour-packages/dwarka-1-day': typeof TourPackagesDwarka1DayRoute
  '/tour-packages/dwarka-2-days': typeof TourPackagesDwarka2DaysRoute
  '/tour-packages/dwarka-gujarat': typeof TourPackagesDwarkaGujaratRoute
  '/tour-packages/dwarka-somnath': typeof TourPackagesDwarkaSomnathRoute
  '/travel-guide/best-time-to-visit': typeof TravelGuideBestTimeToVisitRoute
  '/travel-guide/dwarka-itinerary': typeof TravelGuideDwarkaItineraryRoute
  '/travel-guide/dwarka-local-transport': typeof TravelGuideDwarkaLocalTransportRoute
  '/travel-guide/dwarka-to-somnath': typeof TravelGuideDwarkaToSomnathRoute
  '/travel-guide/how-to-reach-dwarka': typeof TravelGuideHowToReachDwarkaRoute
  '/tour-packages/': typeof TourPackagesIndexRoute
  '/travel-guide/': typeof TravelGuideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/bet-dwarka': typeof BetDwarkaRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact-us': typeof ContactUsRoute
  '/dharamshala-booking': typeof DharamshalaBookingRoute
  '/faq': typeof FaqRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/nageshwar-temple': typeof NageshwarTempleRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sightseeing': typeof SightseeingRoute
  '/taxi-service': typeof TaxiServiceRoute
  '/temple-darshan': typeof TempleDarshanRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tour-packages/dwarka-1-day': typeof TourPackagesDwarka1DayRoute
  '/tour-packages/dwarka-2-days': typeof TourPackagesDwarka2DaysRoute
  '/tour-packages/dwarka-gujarat': typeof TourPackagesDwarkaGujaratRoute
  '/tour-packages/dwarka-somnath': typeof TourPackagesDwarkaSomnathRoute
  '/travel-guide/best-time-to-visit': typeof TravelGuideBestTimeToVisitRoute
  '/travel-guide/dwarka-itinerary': typeof TravelGuideDwarkaItineraryRoute
  '/travel-guide/dwarka-local-transport': typeof TravelGuideDwarkaLocalTransportRoute
  '/travel-guide/dwarka-to-somnath': typeof TravelGuideDwarkaToSomnathRoute
  '/travel-guide/how-to-reach-dwarka': typeof TravelGuideHowToReachDwarkaRoute
  '/tour-packages': typeof TourPackagesIndexRoute
  '/travel-guide': typeof TravelGuideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/bet-dwarka': typeof BetDwarkaRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact-us': typeof ContactUsRoute
  '/dharamshala-booking': typeof DharamshalaBookingRoute
  '/faq': typeof FaqRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/nageshwar-temple': typeof NageshwarTempleRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sightseeing': typeof SightseeingRoute
  '/taxi-service': typeof TaxiServiceRoute
  '/temple-darshan': typeof TempleDarshanRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tour-packages/dwarka-1-day': typeof TourPackagesDwarka1DayRoute
  '/tour-packages/dwarka-2-days': typeof TourPackagesDwarka2DaysRoute
  '/tour-packages/dwarka-gujarat': typeof TourPackagesDwarkaGujaratRoute
  '/tour-packages/dwarka-somnath': typeof TourPackagesDwarkaSomnathRoute
  '/travel-guide/best-time-to-visit': typeof TravelGuideBestTimeToVisitRoute
  '/travel-guide/dwarka-itinerary': typeof TravelGuideDwarkaItineraryRoute
  '/travel-guide/dwarka-local-transport': typeof TravelGuideDwarkaLocalTransportRoute
  '/travel-guide/dwarka-to-somnath': typeof TravelGuideDwarkaToSomnathRoute
  '/travel-guide/how-to-reach-dwarka': typeof TravelGuideHowToReachDwarkaRoute
  '/tour-packages/': typeof TourPackagesIndexRoute
  '/travel-guide/': typeof TravelGuideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/bet-dwarka'
    | '/cancellation-policy'
    | '/contact-us'
    | '/dharamshala-booking'
    | '/faq'
    | '/hotel-booking'
    | '/nageshwar-temple'
    | '/privacy-policy'
    | '/sightseeing'
    | '/taxi-service'
    | '/temple-darshan'
    | '/terms-and-conditions'
    | '/tour-packages/dwarka-1-day'
    | '/tour-packages/dwarka-2-days'
    | '/tour-packages/dwarka-gujarat'
    | '/tour-packages/dwarka-somnath'
    | '/travel-guide/best-time-to-visit'
    | '/travel-guide/dwarka-itinerary'
    | '/travel-guide/dwarka-local-transport'
    | '/travel-guide/dwarka-to-somnath'
    | '/travel-guide/how-to-reach-dwarka'
    | '/tour-packages/'
    | '/travel-guide/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/bet-dwarka'
    | '/cancellation-policy'
    | '/contact-us'
    | '/dharamshala-booking'
    | '/faq'
    | '/hotel-booking'
    | '/nageshwar-temple'
    | '/privacy-policy'
    | '/sightseeing'
    | '/taxi-service'
    | '/temple-darshan'
    | '/terms-and-conditions'
    | '/tour-packages/dwarka-1-day'
    | '/tour-packages/dwarka-2-days'
    | '/tour-packages/dwarka-gujarat'
    | '/tour-packages/dwarka-somnath'
    | '/travel-guide/best-time-to-visit'
    | '/travel-guide/dwarka-itinerary'
    | '/travel-guide/dwarka-local-transport'
    | '/travel-guide/dwarka-to-somnath'
    | '/travel-guide/how-to-reach-dwarka'
    | '/tour-packages'
    | '/travel-guide'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/bet-dwarka'
    | '/cancellation-policy'
    | '/contact-us'
    | '/dharamshala-booking'
    | '/faq'
    | '/hotel-booking'
    | '/nageshwar-temple'
    | '/privacy-policy'
    | '/sightseeing'
    | '/taxi-service'
    | '/temple-darshan'
    | '/terms-and-conditions'
    | '/tour-packages/dwarka-1-day'
    | '/tour-packages/dwarka-2-days'
    | '/tour-packages/dwarka-gujarat'
    | '/tour-packages/dwarka-somnath'
    | '/travel-guide/best-time-to-visit'
    | '/travel-guide/dwarka-itinerary'
    | '/travel-guide/dwarka-local-transport'
    | '/travel-guide/dwarka-to-somnath'
    | '/travel-guide/how-to-reach-dwarka'
    | '/tour-packages/'
    | '/travel-guide/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BetDwarkaRoute: typeof BetDwarkaRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  ContactUsRoute: typeof ContactUsRoute
  DharamshalaBookingRoute: typeof DharamshalaBookingRoute
  FaqRoute: typeof FaqRoute
  HotelBookingRoute: typeof HotelBookingRoute
  NageshwarTempleRoute: typeof NageshwarTempleRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SightseeingRoute: typeof SightseeingRoute
  TaxiServiceRoute: typeof TaxiServiceRoute
  TempleDarshanRoute: typeof TempleDarshanRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TourPackagesDwarka1DayRoute: typeof TourPackagesDwarka1DayRoute
  TourPackagesDwarka2DaysRoute: typeof TourPackagesDwarka2DaysRoute
  TourPackagesDwarkaGujaratRoute: typeof TourPackagesDwarkaGujaratRoute
  TourPackagesDwarkaSomnathRoute: typeof TourPackagesDwarkaSomnathRoute
  TravelGuideBestTimeToVisitRoute: typeof TravelGuideBestTimeToVisitRoute
  TravelGuideDwarkaItineraryRoute: typeof TravelGuideDwarkaItineraryRoute
  TravelGuideDwarkaLocalTransportRoute: typeof TravelGuideDwarkaLocalTransportRoute
  TravelGuideDwarkaToSomnathRoute: typeof TravelGuideDwarkaToSomnathRoute
  TravelGuideHowToReachDwarkaRoute: typeof TravelGuideHowToReachDwarkaRoute
  TourPackagesIndexRoute: typeof TourPackagesIndexRoute
  TravelGuideIndexRoute: typeof TravelGuideIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bet-dwarka': {
      id: '/bet-dwarka'
      path: '/bet-dwarka'
      fullPath: '/bet-dwarka'
      preLoaderRoute: typeof BetDwarkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dharamshala-booking': {
      id: '/dharamshala-booking'
      path: '/dharamshala-booking'
      fullPath: '/dharamshala-booking'
      preLoaderRoute: typeof DharamshalaBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-booking': {
      id: '/hotel-booking'
      path: '/hotel-booking'
      fullPath: '/hotel-booking'
      preLoaderRoute: typeof HotelBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nageshwar-temple': {
      id: '/nageshwar-temple'
      path: '/nageshwar-temple'
      fullPath: '/nageshwar-temple'
      preLoaderRoute: typeof NageshwarTempleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sightseeing': {
      id: '/sightseeing'
      path: '/sightseeing'
      fullPath: '/sightseeing'
      preLoaderRoute: typeof SightseeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi-service': {
      id: '/taxi-service'
      path: '/taxi-service'
      fullPath: '/taxi-service'
      preLoaderRoute: typeof TaxiServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temple-darshan': {
      id: '/temple-darshan'
      path: '/temple-darshan'
      fullPath: '/temple-darshan'
      preLoaderRoute: typeof TempleDarshanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages/': {
      id: '/tour-packages/'
      path: '/tour-packages'
      fullPath: '/tour-packages/'
      preLoaderRoute: typeof TourPackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages/dwarka-1-day': {
      id: '/tour-packages/dwarka-1-day'
      path: '/tour-packages/dwarka-1-day'
      fullPath: '/tour-packages/dwarka-1-day'
      preLoaderRoute: typeof TourPackagesDwarka1DayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages/dwarka-2-days': {
      id: '/tour-packages/dwarka-2-days'
      path: '/tour-packages/dwarka-2-days'
      fullPath: '/tour-packages/dwarka-2-days'
      preLoaderRoute: typeof TourPackagesDwarka2DaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages/dwarka-gujarat': {
      id: '/tour-packages/dwarka-gujarat'
      path: '/tour-packages/dwarka-gujarat'
      fullPath: '/tour-packages/dwarka-gujarat'
      preLoaderRoute: typeof TourPackagesDwarkaGujaratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages/dwarka-somnath': {
      id: '/tour-packages/dwarka-somnath'
      path: '/tour-packages/dwarka-somnath'
      fullPath: '/tour-packages/dwarka-somnath'
      preLoaderRoute: typeof TourPackagesDwarkaSomnathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-guide/': {
      id: '/travel-guide/'
      path: '/travel-guide'
      fullPath: '/travel-guide/'
      preLoaderRoute: typeof TravelGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-guide/best-time-to-visit': {
      id: '/travel-guide/best-time-to-visit'
      path: '/travel-guide/best-time-to-visit'
      fullPath: '/travel-guide/best-time-to-visit'
      preLoaderRoute: typeof TravelGuideBestTimeToVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-guide/dwarka-itinerary': {
      id: '/travel-guide/dwarka-itinerary'
      path: '/travel-guide/dwarka-itinerary'
      fullPath: '/travel-guide/dwarka-itinerary'
      preLoaderRoute: typeof TravelGuideDwarkaItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-guide/dwarka-local-transport': {
      id: '/travel-guide/dwarka-local-transport'
      path: '/travel-guide/dwarka-local-transport'
      fullPath: '/travel-guide/dwarka-local-transport'
      preLoaderRoute: typeof TravelGuideDwarkaLocalTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-guide/dwarka-to-somnath': {
      id: '/travel-guide/dwarka-to-somnath'
      path: '/travel-guide/dwarka-to-somnath'
      fullPath: '/travel-guide/dwarka-to-somnath'
      preLoaderRoute: typeof TravelGuideDwarkaToSomnathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-guide/how-to-reach-dwarka': {
      id: '/travel-guide/how-to-reach-dwarka'
      path: '/travel-guide/how-to-reach-dwarka'
      fullPath: '/travel-guide/how-to-reach-dwarka'
      preLoaderRoute: typeof TravelGuideHowToReachDwarkaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BetDwarkaRoute: BetDwarkaRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  ContactUsRoute: ContactUsRoute,
  DharamshalaBookingRoute: DharamshalaBookingRoute,
  FaqRoute: FaqRoute,
  HotelBookingRoute: HotelBookingRoute,
  NageshwarTempleRoute: NageshwarTempleRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SightseeingRoute: SightseeingRoute,
  TaxiServiceRoute: TaxiServiceRoute,
  TempleDarshanRoute: TempleDarshanRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TourPackagesDwarka1DayRoute: TourPackagesDwarka1DayRoute,
  TourPackagesDwarka2DaysRoute: TourPackagesDwarka2DaysRoute,
  TourPackagesDwarkaGujaratRoute: TourPackagesDwarkaGujaratRoute,
  TourPackagesDwarkaSomnathRoute: TourPackagesDwarkaSomnathRoute,
  TravelGuideBestTimeToVisitRoute: TravelGuideBestTimeToVisitRoute,
  TravelGuideDwarkaItineraryRoute: TravelGuideDwarkaItineraryRoute,
  TravelGuideDwarkaLocalTransportRoute: TravelGuideDwarkaLocalTransportRoute,
  TravelGuideDwarkaToSomnathRoute: TravelGuideDwarkaToSomnathRoute,
  TravelGuideHowToReachDwarkaRoute: TravelGuideHowToReachDwarkaRoute,
  TourPackagesIndexRoute: TourPackagesIndexRoute,
  TravelGuideIndexRoute: TravelGuideIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
